// Importing necessary types and libraries from Next.js and external packages
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Importing global CSS styles
import { Toaster } from "react-hot-toast"; // Importing toast notification component


// Configuring the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

// Defining metadata for the HTML head of the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component that wraps the entire application content
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // HTML document structure
    <html lang="en">
      {/* Body of the HTML document */}
      <body className={inter.className}>
        {/* Toast notification component rendered at the top-right corner */}
        <Toaster position="top-right" />
        {/* Content of the application passed as children */}
        {children}
      </body>
    </html>
  );
}
